#!/bin/bash
count=0
if [ "$( aws iam list-virtual-mfa-devices | jq '.VirtualMFADevices[].SerialNumber' | wc -l)" -gt "0" ];then
  count=$((count+1))
fi
if [ "$count" -eq 0 ]; then
    echo "2.8 FAILED"
else
    echo "PASSED"
fi
