#!/bin/bash
aws iam generate-credential-report
count=0
if [ "$( aws iam get-credential-report --query 'Content' --output text | base64 -d | cut -d, -f1,4,8 | wc -l)" -eq "0" ]; then
     count=$((count+1))
fi
if [ "$count" -eq 0 ]; then
    echo "1.1 PASSED"
else
    echo "FAILED"
fi
