#!/bin/sh
# ** AUTO GENERATED **

PL=$(aws iam get-account-password-policy | grep "MinimumPasswordLength")
NOW='        "MinimumPasswordLength": 15,'

if [ "$NOW" = "$PL" ]
then
   echo "PASSED"
else
   echo "FAILED"
fi
