#!/bin/sh
# ** AUTO GENERATED **

AME=$( aws iam get-account-summary | grep "AccountMFAEnabled" )
NOW='        "AccountMFAEnabled": 0,'

if [ "$NOW" = "$AME" ]
then
   echo "1_14 PASSED"
else
   echo "FAILED"
fi
