#!/bin/bash
count=0
for S3BName in `aws cloudtrail describe-trails |  jq '.trailList[].S3BucketName' | sed 's/"//g'`;
do
if [ "$(aws s3api get-bucket-logging --bucket  $S3BName | wc -l)" -eq "0" ]; then
 count=$((count+1))
#    echo "2.6  Failed"
#    echo "Passed" 
fi 
done
if [ "$count" -ne "0" ]; then
echo "Failed"
else 
echo "Passed"
fi 
