#!/bin/bash
count=0
for TrailName in `aws cloudtrail describe-trails | jq '.trailList[].Name' | sed 's/"//g'`;
do
if [ "$(aws cloudtrail describe-trails | grep IsMultiRegionTrail | grep true)" ]; then
 if ["$(aws cloudtrail get-trail-status --name $TrailName | grep IsLogging | grep true)"];then
   if ["$(aws cloudtrail get-event-selectors --trail-name $TrailName | jq '.EventSelectors[].IncludeManagementEvents' | grep true)"];then
      if ["$(aws cloudtrail get-event-selectors --trail-name $TrailName | jq '.EventSelectors[].ReadWriteType' | grep All)"];then
	     for logGroupName in ` aws logs describe-log-groups | jq '.logGroups[].logGroupName' | sed 's/"//g'`;
		 do
		 for MetricName in `aws logs describe-metric-filters --log-group-name "$logGroupName"`;
		 do
		 if ["$(aws cloudwatch describe-alarms --query 'MetricAlarms[?MetricName== `$MetricName`]' | sed -r 's/(\[|\])//g' | sed '/^$/d' | wc -l)" -gt "0"];then
		  count=$((count+1))
         fi
		 done
		 done
	  else
		 echo "ReadWriteType is not set in ALL : FAiled"
	  fi 
    else
	     echo "EventSelectors is not set in True : FAiled"
	fi
  else
	  echo "IsLogging is not set in True : FAiled" 
  fi
else
      echo "IsMultiRegionTrail is not set in True : FAiled" 
fi
done
if [ "$count" -eq 0 ]; then
    echo "FAILED"
	else
	echo "PASSED"
fi
